/*
 * Copyright 2025 CloudWeGo Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package flow

var locationAdjacencyMap = map[string]map[string]float64{
	"奇幻园林": {
		"幻想世界": 10,
		"未来世界": 7,
		"冒险岛":  6,
		"宝贝港湾": 8,
		"入口大街": 3,
	},
	"幻想世界": {
		"奇幻园林":    10,
		"未来世界":    6,
		"宝贝港湾":    8,
		"热情小动物城市": 5,
		"玩具的故事":   3,
	},
	"未来世界": {
		"幻想世界":  6,
		"奇幻园林":  7,
		"玩具的故事": 4,
		"入口大街":  7,
	},
	"冒险岛": {
		"奇幻园林": 6,
		"宝贝港湾": 5,
		"入口大街": 6,
	},
	"宝贝港湾": {
		"幻想世界": 8,
		"冒险岛":  5,
		"奇幻园林": 8,
	},
	"玩具的故事": {
		"幻想世界": 3,
		"未来世界": 4,
	},
	"热情小动物城市": {
		"幻想世界": 5,
	},
	"入口大街": {
		"奇幻园林": 3,
		"冒险岛":  6,
		"未来世界": 7,
	},
}

var attractions = []Activity{
	{
		Name:               "家勒比海贼——沉船宝贝之战",
		Desc:               "游客必须为\n所有身高\n适合年龄\n所有年龄\n\n惊险程度\n小幅降落, 高音量, 黑暗, 刺激。伙计们，来加入库克船长的海盗队伍，向海洋进发，来一场寻宝之旅，沿途还会遇上怪兽呢！",
		Type:               ActivityTypeAttraction,
		Location:           "宝贝港湾",
		OpenTime:           "上午 8:30",
		CloseTime:          "晚上 9:00",
		Duration:           10,
		HasPriorityAccess:  true,
		PriorityAccessCost: 180,
		QueueTime:          20,
	},
	{
		Name:      "冒险家独木舟",
		Desc:      "游客必须为\n所有身高\n适合年龄\n儿童, 8-13岁少年, 青少年, 成人\n\n惊险程度\n水花四溅。登上探险家独木舟，划着船桨，开启在“宝贝港湾”和“冒险岛”两大主题园区的刺激探险之旅。",
		Type:      ActivityTypeAttraction,
		Location:  "冒险岛",
		OpenTime:  "上午 9:30",
		CloseTime: "下午 4:00",
		Duration:  10,
		QueueTime: 5,
	},
	{
		Name:               "抱抱熊飞天赛车",
		Desc:               "游客必须为\n120厘米或以上\n适合年龄\n儿童, 8-13岁少年, 青少年, 成人\n\n惊险程度\n刺激。在好朋友三角龙特蕾西的帮助下，抱抱熊将邀请大家坐上遥控飞天赛车，在长长的“U”型轨道上开启一段精彩刺激的冒险旅程。",
		Type:               ActivityTypeAttraction,
		Location:           "玩具的故事",
		MinHeight:          120,
		OpenTime:           "上午 8:30",
		CloseTime:          "晚上 9:00",
		Duration:           10,
		HasPriorityAccess:  true,
		PriorityAccessCost: 180,
		QueueTime:          40,
	},
	{
		Name:               "无敌牛仔派对",
		Desc:               "游客必须为\n81厘米或以上\n适合年龄\n儿童, 8-13岁少年, 青少年, 成人\n\n惊险程度\n旋转。跳上怀旧的西部马车，让小马们拉着你，踏着欢快的音乐，一同摇摆。就在玩具的故事主题园区。",
		Type:               ActivityTypeAttraction,
		Location:           "玩具的故事",
		MinHeight:          81,
		OpenTime:           "上午 8:30",
		CloseTime:          "晚上 9:00",
		Duration:           10,
		HasPriorityAccess:  true,
		PriorityAccessCost: 140,
		QueueTime:          30,
	},
	{
		Name:               "热情小动物城市：热力追踪",
		Desc:               "游客必须为\n所有身高\n适合年龄\n所有年龄\n\n惊险程度\n黑暗, 小幅降落。*使用该尊享卡的游客可快速进入热情小动物城市。请注意，从尊享卡通道进入热情小动物城市：热力追踪景点时，将无法体验完整的排队区场景。\n\n渴望尝试一切的你，将作为动物城警察局的新警员，加入巡逻，不料途中突发案件：坏绵羊越狱，与同伙一起绑架大明星夏奇羊！朱迪和尼克邀你一起驾驶警车，飞身加入环环相扣的热力追踪：疾驰冰川镇、穿梭撒哈拉广场，飞越雨林跑道……一路沉浸在热烈疯狂的追逐中！",
		Type:               ActivityTypeAttraction,
		Location:           "热情小动物城市",
		OpenTime:           "上午 8:30",
		CloseTime:          "晚上 9:00",
		Duration:           10,
		HasPriorityAccess:  true,
		PriorityAccessCost: 180,
		QueueTime:          70,
	},
	{
		Name:               "八个大高人矿山车",
		Desc:               "游客必须为\n97厘米或以上\n适合年龄\n儿童, 8-13岁少年, 青少年, 成人\n\n惊险程度\n急速降落, 刺激。适合全家共同体验的过山车项目——穿梭在《白雪公主和八个大高人》的钻石矿山中。",
		Type:               ActivityTypeAttraction,
		Location:           "幻想世界",
		MinHeight:          97,
		OpenTime:           "上午 8:30",
		CloseTime:          "晚上 9:00",
		Duration:           10,
		HasPriorityAccess:  true,
		PriorityAccessCost: 180,
		QueueTime:          90,
	},
	{
		Name:               "派斯音速太阳系营救",
		Desc:               "游客必须为\n所有身高\n适合年龄\n所有年龄\n\n惊险程度\n黑暗。投身战斗，竭尽全力消灭索克天王手下骇人的机器人部队，拯救外星人的星球！",
		Type:               ActivityTypeAttraction,
		Location:           "未来世界",
		OpenTime:           "上午 8:30",
		CloseTime:          "晚上 9:00",
		Duration:           10,
		HasPriorityAccess:  true,
		PriorityAccessCost: 140,
		QueueTime:          5,
	},
	{
		Name:               "超速大飞轮",
		Desc:               "游客必须为\n122厘米或以上\n适合年龄\n儿童, 8-13岁少年, 青少年, 成人\n\n惊险程度\n刺激, 黑暗, 急速降落。进入“创”的电子网络世界，随着极速光轮、极速转向，全力奔驰吧！",
		Type:               ActivityTypeAttraction,
		Location:           "未来世界",
		MinHeight:          122,
		OpenTime:           "上午 8:30",
		CloseTime:          "晚上 9:00",
		Duration:           10,
		HasPriorityAccess:  true,
		PriorityAccessCost: 180,
		QueueTime:          50,
	},
	{
		Name:      "背着背包的飞行器",
		Desc:      "游客必须为\n112厘米或以上\n适合年龄\n所有年龄\n\n惊险程度\n旋转。加速，再加速，带着这次未来之旅令人激动的兴奋感出发！",
		Type:      ActivityTypeAttraction,
		Location:  "未来世界",
		MinHeight: 112,
		OpenTime:  "上午 8:30",
		CloseTime: "晚上 9:00",
		Duration:  10,
		QueueTime: 40,
	},
	{
		Name:      "太空幸会神秘生物",
		Desc:      "游客必须为\n所有身高\n适合年龄\n所有年龄。阿咯哈（Aloha）! 快来太空观察站“幸会神秘生物”！不要担心，请跟这个毛茸茸的调皮蓝色小外星人打招呼吧，他保证让您捧腹大笑",
		Type:      ActivityTypeAttraction,
		Location:  "未来世界",
		OpenTime:  "上午 11:00",
		CloseTime: "晚上 7:00",
		Duration:  10,
		QueueTime: 15,
	},
	{
		Name:               "飞吧地平线",
		Desc:               "游客必须为\n102厘米或以上\n适合年龄\n儿童, 8-13岁少年, 青少年, 成人。来一场令人兴奋的飞行，以前所未有的方式见证这个神奇的世界吧！",
		Type:               ActivityTypeAttraction,
		Location:           "冒险岛",
		MinHeight:          102,
		OpenTime:           "上午 8:30",
		CloseTime:          "晚上 9:00",
		Duration:           10,
		HasPriorityAccess:  true,
		PriorityAccessCost: 180,
		QueueTime:          60,
	},
}

var performances = []Activity{
	{
		Name:      "风暴在上：库克船长之惊天特技大冒险",
		Desc:      "舞台上，库克船长神出鬼没、诙谐逗趣，又勇敢无畏，让人激动不已，观众看得忍俊不禁、惊呼声欢笑声此起彼伏。\n\n在“凡迭戈剧院”，当真正的库克船长发现有位演员在舞台上扮演他时，他立誓要让这位冒名顶替者以及在座的观众见识一下真正的海盗究竟有多大的本事。但是库克船长一露面，就引起了英国皇家海军的注意，他们在舞台上发起猛攻，展开了追捕。全场很快陷入一片令人捧腹的混乱之中。海盗、水手和演员们在舞台上激烈厮杀，以惊人特技上演英勇决斗。\n\n混战持续升级，屏气凝神，惊心动魄的结局即将上演！一股向“宝贝港湾”逼近的飓风猛烈地吹袭剧院，库克船长和他的对手被刮到半空中，最扣人心弦的空中击剑大战就在眼前！",
		Type:      ActivityTypePerformance,
		Location:  "宝贝港湾",
		Duration:  30,
		TimeTable: []string{"10:30", "11:10", "11:50", "13:00", "13:40", "14:20", "16:00", "16:30", "17:10", "17:50"},
	},
	{
		Name:      "冰冻三尺：欢唱盛会",
		Desc:      "进入“林间剧场”，您将在“幻想世界”里体验到阿伦黛尔王国的魅力。快看！安娜、艾莎、克斯托夫，还有雪宝都在这！他们即将开启新的冒险旅程，去探索阿伦黛尔之外的广袤大陆。\n\n他们讲述回味不尽的故事，演唱您最喜爱的歌曲包括《冰冻三尺2》最新曲目，还会邀请您加入其中。一起高歌的人越多，体验就越奇妙！您的歌声带给他们勇气，去拯救阿伦黛尔王国",
		Type:      ActivityTypePerformance,
		Location:  "幻想世界",
		Duration:  20,
		TimeTable: []string{"10:45", "11:30", "13:15", "14:00", "14:45", "15:30", "16:30", "17:15"},
	},
	{
		Name:      "梦幻故事会",
		Desc:      "一个说故事的剧团诙谐地用木偶、歌唱叙述了他们最爱的故事。",
		Type:      ActivityTypePerformance,
		Location:  "幻想世界",
		Duration:  20,
		TimeTable: []string{"09:45", "13:20", "15:20"},
	},
	{
		Name:      "梦幻节",
		Desc:      "一起和朋友还有吟游剧团的朋友们用特别的舞蹈开启美好神奇的一天。",
		Type:      ActivityTypePerformance,
		Location:  "幻想世界",
		Duration:  15,
		TimeTable: []string{"11:00"},
	},
	{
		Name:      "吟游剧团",
		Desc:      "吟游剧团是一群快乐的音乐家，带着活力和热情唱着歌曲。他们所演奏的中国传统乐器和西方手风琴展现了幻想世界的独特魅力。\n此外，当小熊维尼和他的好朋友们到来时，他们会加入吟游剧团，开启一场百亩森林里的欢庆会。",
		Type:      ActivityTypePerformance,
		Location:  "幻想世界",
		Duration:  15,
		TimeTable: []string{"14:30", "16:15"},
	},
	{
		Name:      "复仇者小分队培训行动",
		Desc:      "你相信自己有潜力成为复仇者小分队的一员吗？复仇者小分队正在招兵买马，打造新一代地球保卫者。\n\n想要加入的伙伴们可以集结在舞台，参与培训。你将有机会在复仇者小分队的成员和探员们的指导下，练就成为复仇者小分队新成员的必须技能。",
		Type:      ActivityTypePerformance,
		Location:  "未来世界",
		Duration:  15,
		TimeTable: []string{"11:00", "12:45", "14:00", "15:15", "17:00"},
	},
	{
		Name:      "奇幻冬日巡游",
		Desc:      "朋友们将领航整个奇幻冬日巡游，朋友们将会在后面的巡游花车中和大家见面。\n\n巡游中，有人在冰川镇享受雪上机车带来的乐趣；有人在雪中共舞；有人一家正享受着冬日庆典；当然，这里少不了冰冻三尺的主要角色！她们正在阿伦黛尔王国的冬日魔法中尽情狂欢。\n\n夜间场次的巡游会配合灵动绚丽的灯光，带来不同以往的沉浸体验。",
		Type:      ActivityTypePerformance,
		Location:  "奇幻园林",
		Duration:  15,
		TimeTable: []string{"14:15", "18:20"},
	},
	{
		Name:      "金色童话盛典",
		Desc:      "欣赏您最喜爱的公主们倾情上演的的音乐舞台盛宴，领略奇妙魔力和动人乐曲。一同前往“奇幻童话城堡”前的“奇幻园林”，观赏精彩绝伦的日间演出。\n\n不同年龄段的游客将可以透过可爱的朋友绝美的演出服装和难忘的美妙音乐兴高采烈地融入到迪士尼经典的娱乐庆典中。快来亲身感受这有趣浪漫、欢乐刺激的体验吧，让我们一起做一个“永远幸福美满”的美梦！",
		Type:      ActivityTypePerformance,
		Location:  "奇幻园林",
		Duration:  20,
		TimeTable: []string{"11:15", "13:15", "15:15", "16:30"},
	},
	{
		Name:      "童话专列",
		Desc:      "火车主题巡游，满载幻想、趣味和音乐，快加入乐园 A 的巡游之旅吧！巡游欢乐无穷，众多朋友逐一向你走来，米奇将在火车头驾驶列车，而随后的梦幻花车均取材自经典迪士尼电影，为您带来熟悉的朋友和醉人的音乐。\n\n童话专列将“驶过”全球主题乐园中最长的巡游路线，为所有年龄段的游客带来欢笑与惊喜。",
		Type:      ActivityTypePerformance,
		Location:  "奇幻园林",
		Duration:  14,
		TimeTable: []string{"15:45"},
	},
	{
		Name:               "奇梦之光幻影秀",
		Desc:               "踏入光影交织的奇梦，点亮你心中的光。\n\n一场新锐科技与光影艺术编织的童话奇梦，在烟花、火焰、水幕、激光与投影的流转互动中，呈现360度沉浸式体验。\n\n让你变为主角置于光影之中。跟着朋友，一起走入一段跌宕起伏的旅程。开篇：你就是光 - 每个人心中都有一道光，引领梦想，照亮前方。\n\n第二篇：点亮梦想 - 光芒点燃追寻梦想的热情。\n\n第三篇：光芒不熄 - 追梦路上，直面逆境与险阻。\n\n第四篇：冲破黑暗 - 点亮心中光芒，召唤内心英雄。\n\n第五篇：最初的你 - 光明战胜黑暗，点亮最初的纯与真。\n\n第六篇：坚定向光 - 紧握心中信念之光，坚定前行。\n\n终篇：你就是光 - 一个更璀璨的未来，由我们点亮!",
		Type:               ActivityTypePerformance,
		Location:           "奇幻园林",
		Duration:           20,
		TimeTable:          []string{"21:00"},
		HasPriorityAccess:  true,
		PriorityAccessCost: 299,
	},
	{
		Name:      "唐式太极",
		Desc:      "和朋友们在奇幻园林一起练习平衡和身心的和谐。这是一个与身着传统服装的的朋友在传统音乐中互动的奇妙经历。",
		Type:      ActivityTypePerformance,
		Location:  "奇幻园林",
		Duration:  15,
		TimeTable: []string{"10:15", "12:00"},
	},
}

var restaurants = []Activity{
	{
		Name:      "船长烧烤",
		Desc:      "西式, 中式, 小食, 素食可选, 纪念品, 咖啡 菜系\n家庭餐, 儿童餐, 快餐服务。这家餐厅的景致和它的美食一样令人惊艳！更特别的是，食客可以通过开放式厨房亲眼看到主厨烹饪美食的精彩时刻。同时，食客们可以感受到“家勒比海贼——沉船宝贝之战”的战场。¥¥ (人均 人民币51 - 100 )",
		Type:      ActivityTypeRestaurant,
		Location:  "宝贝港湾",
		OpenTime:  "10:30",
		CloseTime: "20:00",
	},
	{
		Name:      "蓝莓熊餐盒",
		Desc:      "西式, 小食, 纪念品, 咖啡, 披萨 菜系\n小食亭, 独特/主题餐饮。这家以玩具的故事为主题的互动游戏场所，还可以享用到“野餐式”的丰富餐饮、形状可爱的披萨和主题甜品。¥¥ (人均 人民币51 - 100 )",
		Type:      ActivityTypeRestaurant,
		Location:  "玩具的故事",
		OpenTime:  "11:00",
		CloseTime: "18:00",
	},
	{
		Name:      "好友欢庆堂",
		Desc:      "中式, 小食, 素食可选, 纪念品 菜系\n家庭餐, 儿童餐, 快餐服务。朋友们在冒险的旅途中，发现了许多新鲜的食材，他们展示才华，用经典的烧烤方式烹制和自然风味调味，他们在大自然享受欢乐，分享美味的食物来庆祝他们的友谊。他们的冒险故事启发了我们在这里制作美食...”好友欢庆堂”将带给你乐趣和惊喜。快来餐厅欢享美味，畅寻萌物吧!¥¥¥ (人均 人民币101 - 300)",
		Type:      ActivityTypeRestaurant,
		Location:  "冒险岛",
		OpenTime:  "10:30",
		CloseTime: "20:00",
	},
	{
		Name:           "皇室宴会厅",
		Desc:           "西式, 素食可选, 纪念品, 咖啡 菜系\n邂逅朋友, 接受预订, 家庭餐, 儿童餐, 点餐服务。皇家宴会厅是亚洲唯一一家坐落于城堡内的餐厅。\n\n步入皇室宴会厅，就像置身梦幻的童话世界，让您在公主故事的奇妙氛围中，和最爱的朋友不期而遇，更能与家人朋友一起尊享城堡内的盛宴，创造专属于您的难忘时刻。¥¥¥¥ (人均 人民币301 - 500)",
		Type:           ActivityTypeRestaurant,
		Location:       "幻想世界",
		OpenTime:       "11:30",
		CloseTime:      "19:30",
		RequireBooking: true,
	},
	{
		Name:      "小藤树食栈",
		Desc:      "中式, 小食, 素食可选, 纪念品, 清真食品 (请提前预订), 亚洲, 西式 菜系\n家庭餐, 儿童餐, 快餐服务, 独特/主题餐饮, 外带\n\n¥¥ (人均 人民币51 - 100 )。欢迎来到老藤树食栈，这里的设计风格取材自影片《头发的故事》的小鸭子酒馆，丰富的细节设计将重现电影中喧嚣吵闹的环境，是粉丝的朝圣之地！游客可以在郁郁葱葱的树林中美餐一顿。",
		Type:      ActivityTypeRestaurant,
		Location:  "幻想世界",
		OpenTime:  "10:30",
		CloseTime: "18:30",
	},
	{
		Name:      "好伙伴美味市集",
		Desc:      "中式, 小食, 素食可选, 纪念品, 咖啡 菜系\n家庭餐, 儿童餐, 快餐服务\n\n¥¥¥ (人均 人民币101 - 300)。在这个街坊美食广场，有四种不同风格的美食任君选择，各种特色美食包括炖菜、烧烤以及面条等各色招牌菜。",
		Type:      ActivityTypeRestaurant,
		Location:  "入口大街",
		OpenTime:  "10:30",
		CloseTime: "21:00",
	},
	{
		Name:      "乡村厨房",
		Desc:      "披萨, 中式, 小食, 素食可选, 纪念品, 西式, 冰淇淋 菜系\n家庭餐, 儿童餐, 快餐服务\n\n¥¥ (人均 人民币51 - 100 )。乡村厨房拥有如同老木偶匠盖比特工作室一般的设计风格，多彩的皮诺丘历险壁画使这个亲切的家庭式餐厅充满活力。高颜值披萨是这里的特色招牌, 除此之外, 家庭盛宴和品种丰富的各类面食和饭食都是带上家人聚餐的上佳之选。快和你的家人一起在奇妙世界沉浸式体验一番吧!",
		Type:      ActivityTypeRestaurant,
		Location:  "幻想世界",
		OpenTime:  "10:30",
		CloseTime: "20:00",
	},
	{
		Name:      "星露谷餐厅",
		Desc:      "西式, 汉堡炸鸡, 小食, 素食可选, 纪念品, 咖啡, 清真食品 (请提前预订), 中式 菜系\n家庭餐, 儿童餐, 快餐服务\n\n¥¥ (人均 人民币51 - 100 )。在星露谷餐厅，您可以探索各类特色美食，包括炸鸡柳、薯条和让人流连忘返的汉堡。广受好评的复仇者小分队汉堡不容错过。",
		Type:      ActivityTypeRestaurant,
		Location:  "未来世界",
		OpenTime:  "10:30",
		CloseTime: "21:00",
	},
}
